# 校验节点软件系统及硬件系统、安装必要基础组件、docker、kubeadm、kubelet、kubectl
- hosts: 
  - all
  roles:
  - prepare/base
  - prepare/docker
  - prepare/kubernetes

# 进行apiserver负载均衡
- hosts: 
  - new-worker
  roles:
  - load-balancer

# 初始化worker节点
- hosts: 
  - new-worker
  roles:
  - kube-worker

# 标记各节点角色
- hosts: 
  - new-worker
  roles:
  - post