# 分发证书
- name: 获取 kubernetes 相关证书
  slurp:
    src: /etc/kubernetes/pki/{{ item }}
  with_items:
  - ca.crt
  - ca.key
  - apiserver.crt
  - apiserver.key
  - apiserver-kubelet-client.crt
  - apiserver-kubelet-client.key
  - sa.key
  - sa.pub
  - kube-controller-manager.crt
  - kube-scheduler.crt
  - kube-scheduler.key
  - front-proxy-ca.crt
  - front-proxy-ca.key
  - front-proxy-client.crt
  - front-proxy-client.key
  - admin.crt
  - admin.key
  - kubelet.key
  - kube-openssl.cnf
  register: kubernetes_certs
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 分发 kubernetes 相关证书到 master 节点
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ kubernetes_certs.results }}"
  when: inventory_hostname != groups['kube-master'][0]