- name: 创建 kubernetes 相关目录
  file: 
    name: /etc/kubernetes/pki
    state: directory

- block:
  # 获取密钥状态
  - include_tasks: certs_stat.yml
  # 生成公共证书
  - include_tasks: common.yml
  when: inventory_hostname == groups['kube-master'][0]

# 分发证书
- include_tasks: distribute.yml

# 各节点分别生成 kubelet 证书
- include_tasks: respective.yml

- name: 读取 kubelet.conf 文件 stat 信息
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- include_tasks: kubeconfig.yml
  when: kubelet_conf_stat.stat.exists