# 提权操作
ansible_become: true
# 安装模式
install_mode: online

#----------------------------------------------- 基础参数 -------------------------------------------------#
# 当前节点ip
CURRENT_HOST_IP: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}{{ hostvars[inventory_hostname]['ansible_host'] }}{% else %}{{ inventory_hostname }}{% endif %}"
# 负载均衡模式(有nginx和haproxy,slb三个选项。默认使用nginx，也可以选择haproxy时必须设置VIP)
lb_mode: nginx
# apiserver ip
KUBE_APISERVER_IP: >-
  {% if lb_kube_apiserver_ip is not defined %}
    127.0.0.1
  {% else %}
    {{ lb_kube_apiserver_ip }}
  {% endif %}

# 加入集群token
kubeadm_token: "abcdef.0123456789abcdef"

# 负载后的apiserver端口号
lb_kube_apiserver_port: 8443

# k8s 集群 master 节点证书配置，可以添加多个ip和域名（比如增加公网ip和域名）
kube_master_external_ip:
- "8.8.8.8"

kube_master_external_demain:
- "kubernetes.io"

# Pod根容器
pod_infra_container_image: gcr.azk8s.cn/google_containers/pause:3.1
# kubernetes各组件镜像仓库前缀
kube_image_repository: gcr.azk8s.cn/google_containers
# kubernetes版本
kube_version: 1.15.5
# 集群内部dns域名
kube_dns_domain: cluster.local
# 集群pod ip段
kube_pod_subnet: 10.244.0.0/18
# 集群service ip段
kube_service_subnet: 10.244.64.0/18
KUBERNETES_SERVICE_IP: "{{ kube_service_subnet | ipaddr('net') | ipaddr(1) | ipaddr('address') }}"
CLUSTER_DNS_SERVICE_IP: "{{ kube_service_subnet | ipaddr('net') | ipaddr(10) | ipaddr('address') }}"
# NodePort端口范围
kube_service_node_port_range: 30000-32767
# 资源保留相关配置
eviction_hard_imagefs_available: 15%
eviction_hard_memory_available: 100Mi
eviction_hard_nodefs_available: 10%
eviction_hard_nodefs_inodes_free: 5%
# 默认使用kube-proxy的 'iptables' 模式，可选 'ipvs' 模式(experimental)
kube_proxy_mode: "iptables"

# Kubelet 根目录
kubelet_root_dir: "/var/lib/kubelet"

# node节点最大pod 数
kube_max_pods: 110