# - name: 删除centos默认安装
#   yum: 
#     name: 
#     - firewalld
#     - python-firewall
#     - firewalld-filesystem
#     state: absent
#     disablerepo: "*"

- name: 判断 firewalld 是否安装
  shell: >
    systemctl status firewalld | grep active || echo "not be found"
  register: firewalld_already_installed

- name: 禁用防火墙
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: '"active" in firewalld_already_installed.stdout'

- name: 校验安装模式
  assert:
    that: base_yum_repo is defined or base_yum_repo != None
    msg: "当前安装模式为 {{ install_mode }}，请设置变量 base_yum_repo 。"
  when: install_mode != 'online'

- block:
  - name: 备份原有 yum 源
    raw: mv /etc/yum.repos.d /etc/yum.repos.d.orig.$(date '+%Y%m%dT%H%M%S')

  - name: 创建相关目录
    file:
      path: /etc/yum.repos.d
      state: directory

  - name: 添加基础 yum 仓库
    yum_repository:
      name: base
      description: Custom Repository
      baseurl: "{{ base_yum_repo }}"
      enabled: yes
      gpgcheck: no
      state: present
  when: base_yum_repo is defined and base_yum_repo != None

# - name: 添加 epel 仓库
#   yum: 
#     name: epel-release 
#     state: latest
- name: 添加 epel 仓库
  yum_repository:
    name: epel
    description: EPEL Repository
    baseurl: "{{ epel_yum_repo }}"
    enabled: yes
    gpgcheck: no
    state: present

- name: 刷新 yum 缓存
  raw: yum clean all && yum makecache fast

- name: 安装基础软件包
  yum: 
    name: 
    - git
    - iotop
    - htop
    - net-tools
    - sysstat
    - conntrack
    - libseccomp
    - conntrack-tools                 # ipvs 模式需要
    - ipset                           # ipvs 模式需要
    - ipvsadm                         # ipvs 模式需要
    - nfs-utils                       # 挂载nfs 共享文件需要 (创建基于 nfs的 PV 需要)
    - jq                              # 轻量JSON处理程序
    - socat                           # 用于port forwarding
    - bash-completion                 # bash命令补全工具，需要重新登录服务器生效
    - device-mapper-persistent-data   # docker会用到
    - lvm2                            # docker会用到
    - curl                            # 基础工具
    - yum-utils                       # 基础工具
    - nc                              # 使用lb时进行端口判断时会用到
    state: latest

- name: 重新启动 crond 避免因修改时区而导致的作业错乱问题
  service:
    name: crond
    state: restarted
    enabled: yes

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"