- name: 使用 kubeadm 重置节点
  command: kubeadm reset -f
  ignore_errors: true

- name: 停止相关服务
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
  - docker
  - kubelet
  ignore_errors: true

- include_tasks: centos.yml
  when: ansible_distribution in [ 'CentOS','OracleLinux','RedHat' ]

- include_tasks: debian.yml
  when: ansible_distribution in [ 'Ubuntu','Debian' ]

- name: 卸载 docker 相关文件或目录
  mount: 
    path: "{{ item }}"
    state: unmounted
  with_items:
  - /var/run/docker
  - /var/lib/docker/overlay
  - /var/run/docker/netns/default

- name: 删除 docker 相关目录
  file: 
    name: "{{ item }}"
    state: absent
  with_items:
  - "{{ docker_storage_dir }}"
  - /etc/docker
  - /var/lib/docker
  - /var/run/docker
  - /usr/share/bash-completion/completions/docker

- name: 卸载 kubelet 相关目录
  mount: 
    path: "{{ item }}"
    state: unmounted
  with_items:
  - /var/lib/kubelet 
  - /var/run/kubelet 

- name: 删除 kubelet 相关文件或目录
  file: 
    name: "{{ item }}"
    state: absent
  with_items:
  - "{{ kubelet_root_dir }}"
  - "{{ ansible_env.HOME }}/.kube"
  - /etc/kubernetes
  - /var/lib/kubelet
  - /var/run/kubelet
  - /usr/share/bash-completion/completions/kubectl
  - /etc/systemd/system/kubelet.service.d/20-kubelet-override.conf

- name: 移除其他相关文件或目录
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/lib/etcd
  - /etc/cni/net.d
  - /etc/sysctl.d/95-k8s-sysctl.conf
  - /etc/modules-load.d/10-k8s-modules.conf
  - /run/flannel
  - /etc/calico
  - /var/run/calico
  - /var/lib/calico
  - /var/log/calico
  - /var/run/openvswitch
  - /etc/origin/openvswitch
  - /etc/openvswitch
  - /var/log/openvswitch
  - /etc/cni/net.d/00-kube-ovn.conflist

- name: 删除 ulimits 相关配置
  file: 
    name: "{{ item }} "
    state: absent
  with_items:
  - /etc/systemd/system.conf.d/30-k8s-ulimits.conf

- name: 清理 iptables
  shell: "{{ item }} || true"
  with_items:
  - iptables -F
  - iptables -X
  - iptables -F -t nat
  - iptables -X -t nat
  - iptables -F -t raw
  - iptables -X -t raw
  - iptables -F -t mangle
  - iptables -X -t mangle

- name: 刷新 iptables
  iptables:
    table: "{{ item }}"
    flush: yes
  with_items:
    - filter
    - nat

- name: 清理 ipvsadm
  shell: "{{ item }} || true"
  with_items:
  - ipvsadm --clear

- name: 清除虚拟网卡
  shell: "{{ item }} || true"
  with_items:
  - ip link del docker0
  - ip link del tunl0
  - ip link del flannel.1
  - ip link del cni0
  - ip link del mynet0
  - ip link del kube-bridge
  - ip link del dummy0
  - ip link del kube-ipvs0
  - ip link del cilium_net
  - ip link del cilium_vxlan
  - ip link del ovn0
  - ip link del ovs-system

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- name: 移除添加的 hosts 信息
  blockinfile:
    path: "/etc/hosts"
    state: absent
    follow: yes
    marker: "# Ansible inventory hosts {mark}"

- name: 重启网络
  systemd:
    name: >-
      {% if ansible_os_family == "RedHat" -%}
      network
      {%- elif ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic" -%}
      systemd-networkd
      {%- elif ansible_os_family == "Debian" -%}
      networking
      {%- endif %}
    state: restarted